version: "3"
services:
  server:
    build: .
    container_name: aws-cli
    tty: true
    stdin_open: true
    volumes:
      - ./backup:/tmp/backup
    environment:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      